on:
  push:
    branches:
      master

jobs:
  playground:
    name: container-ci
    runs-on: ubuntu-latest
    env:
      play_env: env
    steps:
      - uses: actions/checkout@v2
      - name: run
        run: |
          echo '${{env.play_env}}'
